SOURCE: hris-import
RULES: cHNldWRvbnltaXphdGlvbnM6CiAgLSBjb2x1bW5zOgogICAgICAtICJlbWFpbCIKICAgIHJlbGF0aXZlVXJsUmVnZXg6ICIvYWRtaW4vcmVwb3J0cy92MS9hY3Rpdml0eS91c2Vycy9hbGwvYXBwbGljYXRpb25zL21lZXQuKiIKcmVkYWN0aW9uczoKICAtIGNvbHVtbnM6CiAgICAgIC0gIm1hbmFnZXJFbWFpbCIK
