SOURCE: outlook-cal
TARGET_HOST: graph.microsoft.com
SOURCE_AUTH_STRATEGY_IDENTIFIER: oauth2_refresh_token
GRANT_TYPE: client_credentials # by default, assumed to be of type 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer'
IDENTIFIER_SCOPE_ID: azure-ad
REFRESH_ENDPOINT: https://login.microsoftonline.com/common/oauth2/token
RESOURCE: https://graph.microsoft.com/
