name: CI - infra (terraform)

on:
  push:
    branches:
      - '**' # should match all branches
    tags-ignore:
      - '**' # all tags; actually, believe this is default behavior when you specify filter for branches but not tags

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.0.8
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform - validate examples/aws-google-workspace'
        working-directory: infra/examples/aws-google-workspace
        run: |
          terraform init
          terraform validate
          
      - name: 'Terraform - validate examples/aws-hris'
        working-directory: infra/examples/aws-hris
        run: |
          terraform init
          terraform validate

      - name: 'Terraform - validate examples/aws-msft-365'
        working-directory: infra/examples/aws-msft-365
        run: |
          terraform init
          terraform validate

      - name: 'Terraform - validate examples/aws-zoom-slack'
        working-directory: infra/examples/aws-zoom-slack
        run: |
          terraform init
          terraform validate

      - name: 'Terraform - validate examples/gcp-bootstrap-cft'
        working-directory: infra/examples/gcp-bootstrap-cft
        run: |
          terraform init
          terraform validate
          
      - name: 'Terraform - validate examples/gcp-bootstrap-simple'
        working-directory: infra/examples/gcp-bootstrap-simple
        run: |
          terraform init
          terraform validate
    
      - name: 'Terraform - validate examples/gcp-dev-personal'
        working-directory: infra/examples/gcp-dev-personal
        run: |
          terraform init
          terraform validate

      - name: 'Terraform - validate examples/gcp-google-workspace'
        working-directory: infra/examples/gcp-google-workspace
        run: |
          terraform init
          terraform validate
          
      - name: 'Terraform - validate examples/gcp-hris'
        working-directory: infra/examples/gcp-hris
        run: |
          terraform init
          terraform validate

      - name: 'Terraform - validate examples/gcp-hris'
        working-directory: infra/examples/gcp-hris
        run: |
          terraform init
          terraform validate
          
