name: CI - infra (terraform)

on:
  push:
    branches:
      - '**' # should match all branches
    tags-ignore:
      - '**' # all tags; actually, believe this is default behavior when you specify filter for branches but not tags

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.0.8
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform - validate dev-personal'
        working-directory: infra/dev-personal
        run: |
          terraform init
          terraform validate

      - name: 'Terraform - validate example-google-workspace'
        working-directory: infra/example-google-workspace
        run: |
          terraform init
          terraform validate

     - name: 'Terraform - validate example-gcp-simple'
       working-directory: infra/example-gcp-simple
       run: |
         terraform init
         terraform validate

     - name: 'Terraform - validate example-gcp-cft'
       working-directory: infra/example-gcp-cft
       run: |
         terraform init
         terraform validate
